name: Snapshot docker build and push

on:
  workflow_run:
    workflows: ["CI - Tests"]
    types: [completed]

concurrency:
  group: snapshot-docker-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

permissions:
  packages: write
  contents: read

jobs:
  docker-build:
    name: 📦 Docker Build and Push
    runs-on: ubuntu-22.04
    if: >-
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch != 'main' &&
      github.event.workflow_run.head_repository.full_name == github.repository &&
      (github.event.workflow_run.event == 'push' || 
       github.event.workflow_run.event == 'workflow_run' || 
       github.event.workflow_run.event == 'pull_request')

    steps:
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Sanitize branch name for Docker tag
        id: sanitize-branch
        run: |
          SAFE_BRANCH_NAME=$(echo "${{ github.event.workflow_run.head_branch }}" | tr '/' '-')
          echo "safe_branch=$SAFE_BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Run Snapshot Docker Build/Push
        uses: pagopa/github-actions-template/payments-flow-docker-snapshot@e67e0ec4bb01d6cb5065e311ba0e1c92c49966a7
        with:
          current_branch: ${{ steps.sanitize-branch.outputs.safe_branch }}